models/aluno.py
from database import db
from flask_login import UserMixin

class Aluno(db.Model, UserMixin):
    __tablename__ = "aluno"
    id = db.Column(db.Integer, primary_key = True)
    nome = db.Column(db.String(100))
    matricula = db.Column(db.String(100))
    senha = db.Column(db.String(100))

    def __init__(self, nome, matricula, senha):
        self.nome = nome
        self.matricula = matricula
        self.senha = senha

models/nota.py
from database import db

class Nota(db.Model):
    __tablename__ = "nota"
    id = db.Column(db.Integer, primary_key = True)
    valor = db.Column(db.Float)

    def __init__(self, id, valor):
        self.id = id
        self.valor = valor

models/turma.py
from database import db

class Turma(db.Model):
    __tablename__ = "turma"
    id = db.Column(db.Integer, primary_key = True)
    turma = db.Column(db.String(100))
    cargahoraria = db.Column(db.Integer)
    
    def __init__(self, id, turma, cargahoraria):
        self.id = id
        self.turma = turma
        self.cargahoraria = cargahoraria

controllers/aluno.py
from flask import Flask, render_template, request, flash, redirect, url_for
from flask import Blueprint
from models.aluno import Aluno
from database import db, lm
from flask_login import login_user, logout_user, login_required

bp_alunos = Blueprint("alunos", __name__, template_folder='templates')

@bp_alunos.route('/login')
def login():
    return render_template('login.html')

@bp_alunos.route('/logoff')
def logoff():
    logout_user()
    return redirect('/')

@bp_alunos.route('/autenticar', methods=['POST'])
def autenticar():
    matricula = request.form.get('matricula')
    senha = request.form.get('senha')
    aluno = Aluno.query.filter_by(matricula=matricula).first()
    if (aluno and aluno.senha == senha):
        login_user(aluno)
        return redirect('listar')

    else:
        flash('Dados incorretos', 'danger')
        return redirect('/')

@bp_alunos.route('/cadastrar', methods=['GET', 'POST'])
def cadastrar():
    if request.method == 'GET':
        return render_template('alunos/alunos_cadastrar.html')
    else:
        nome = request.form.get("nome")
        matricula = request.form.get("matricula")
        senha = request.form.get("senha")
        aluno = Aluno(nome, matricula, senha)
        db.session.add(aluno)
        db.session.commit()
        flash('Dados cadastrados com sucesso!', 'success')
        return redirect(url_for('alunos.listar'))

@bp_alunos.route('/listar', methods=['GET'])
def listar():
    alunos = Aluno.query.all()
    return render_template('alunos/alunos_listar.html', alunos=alunos)
        
@bp_alunos.route('/excluir/<int:id>', methods=['GET', 'POST'])
@login_required
def excluir(id):
  aluno = Aluno.query.get(id)
  if request.method == 'GET':
    return render_template('alunos/alunos_excluir.html', aluno = aluno)
  
  if request.method == 'POST':
    db.session.delete(aluno)
    db.session.commit()
    flash('Usuário excluído com sucesso', 'success')
    return redirect(url_for('alunos.listar'))
    
@bp_alunos.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar(id):
    aluno = Aluno.query.get(id)
    if request.method == 'GET':
        return render_template('alunos/alunos_editar.html', aluno=aluno)
    else:
        aluno.nome = request.form.get("nome")
        aluno.matricula = request.form.get("matricula")
        db.session.add(aluno)
        db.session.commit()
        flash('Dados atualizados com sucesso!', 'success')
        return redirect(url_for('alunos.listar'))

@lm.user_loader
def load_user(id):
    aluno = Aluno.query.filter_by(id=id).first()
    return aluno

main.py
from flask import Flask, render_template, request, flash, redirect, url_for
import pymysql
from database import db, lm
from flask_migrate import Migrate
from models.nota import Nota
from models.turma import Turma
from models.aluno import Aluno
from controllers.aluno import bp_alunos

app = Flask(__name__)
app.register_blueprint(bp_alunos, url_prefix='/alunos')

app.config['SECRET_KEY'] = 'hsdaey7q6eihmsn9816}]'
conexao = 'mysql+pymysql://psi2023_alba:u0ZNtc8AMbiMIr[m@albalopes.tech/psi2023_alba'
app.config['SQLALCHEMY_DATABASE_URI'] = conexao
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)
lm.init_app(app)

migrate = Migrate(app, db)

@app.route('/')
def index():
    return redirect(url_for('alunos.login'))

@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')

@app.route('/add', methods=['GET', 'POST']) 
def add():
    if request.method == 'GET':
        return render_template('nota_add.html')
    else:
        valor = request.form.get('valor')
        obj = Nota(0, valor)
        db.session.add(obj)
        db.session.commit()
        flash('Dados inseridos com sucesso')
        return redirect(url_for('add'))

@app.route('/get')
def get():
    notas = Nota.query.all()
    return render_template('nota_get.html', notas=notas)

@app.errorhandler(401)
def acesso_negado(e):
    flash('Você não tem permissão de acessar essa página', 'danger')
    return redirect('/')

if __name__ == '__main__':
    app.run(debug=True)

templates/acesso_negado.html
<!DOCTYPE html>
<html>
<head>
    <title>Acesso não permitido</title>
    <!-- Inclua os links para os arquivos CSS e JS do Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-4">
               <div class="alert alert-danger" role="alert">
                       Você não tem permissão de acessar essa página. Faça login para prosseguir. 
                </div>
                
                
                <form action="{{url_for('alunos.autenticar')}}" method="post">
                    <div class="form-group">
                        <label for="username">Matrícula</label>
                        <input type="text" class="form-control" id="matricula" name="matricula" placeholder="Digite sua matrícula" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Senha</label>
                        <input type="password" class="form-control" id="senha" name="senha" placeholder="Digite sua senha" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/alunos/alunos_cadastrar.html
{% extends 'base.html' %}

{% block conteudo %}
    <div class="container">
        <h1 class="mt-5">CRUD Aluno</h1>

        <!-- Formulário para criar um novo aluno -->
        <div class="mt-4">
            <h2>Adicionar Aluno</h2>
            <form action="{{url_for('alunos.cadastrar')}}" method="POST">
                <div class="form-group">
                    <label for="nome">Nome:</label>
                    <input type="text" class="form-control" id="nome" name="nome" required>
                </div>
                <div class="form-group">
                    <label for="matricula">Matrícula:</label>
                    <input type="text" class="form-control" id="matricula" name="matricula" required>
                </div>
                <div class="form-group">
                    <label for="senha">Senha:</label>
                    <input type="password" class="form-control" id="senha" name="senha" required>
                </div>
                <button type="submit" class="btn btn-info">Adicionar Aluno</button>
            </form>
        </div>

{% endblock %}

templates/alunos/alunos_editar.html
{% extends 'base.html' %}

{% block conteudo %}
    <div class="container">
        <h1 class="mt-5">Alunos</h1>

        <!-- Formulário para criar um novo aluno -->
        <div class="mt-4">
            <h2>Atualizar</h2>
            <form action="{{url_for('alunos.editar', id=aluno.id)}}" method="POST">
                <div class="form-group">
                    <label for="nome">Nome:</label>
                    <input type="text" class="form-control" id="nome" name="nome" value="{{aluno.nome}}" required>
                </div>
                <div class="form-group">
                    <label for="matricula">Matrícula:</label>
                    <input type="text" class="form-control" id="matricula" name="matricula" value="{{aluno.matricula}}" required>
                </div>
                <button type="submit" class="btn btn-info">Atualizar Aluno</button>
            </form>
        </div>

{% endblock %}

templates/alunos/alunos_excluir.html
{% extends 'base.html' %}

{% block conteudo %}
    <div class="container">
        <h1 class="mt-5">Excluir aluno</h1>
         Você tem certeza que deseja excluir o aluno {{aluno.nome}}? 
         <form method='post' action="{{url_for('alunos.excluir', id=aluno.id)}}"> 
            <input type="submit" value="Sim"  class="btn btn-danger"> 
            <a href="{{url_for('alunos.listar')}}" class="btn btn-info">Cancelar</a> 
        </form> 
    </div>
{% endblock%}

templates/alunos/alunos_listar.html
{% extends 'base.html' %}
{%block conteudo %}
    <div class="container">
        <h1 class="mt-5">Listar Alunos</h1>

        <a href="{{url_for('alunos.cadastrar')}}" class="btn btn-info">Adicionar aluno</a>
        <!-- Tabela para listar alunos existentes -->
        <div class="mt-4">
            <h2>Alunos</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Matrícula</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for aluno in alunos %}
                        <tr>
                            <td>{{ aluno.nome }}</td>
                            <td>{{ aluno.matricula }}</td>
                            <td>
                                <a href="{{url_for('alunos.editar', id=aluno.id)}}" class="btn btn-info">Editar</a>
                                <a href="{{url_for('alunos.excluir', id=aluno.id)}}" class="btn btn-danger">Apagar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}
</body>
</html>

templates/base.html
<html>
	    <head>  
            <!-- Inclua os links para os arquivos CSS e JS do Bootstrap -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        
	        <title>Nossa Escola!</title>
	    </head>
	    <body>

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Nossa Escola</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" href="{{url_for('alunos.listar')}}">Alunos <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Turmas</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Notas</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">             
                      <a class="nav-link" href="{{url_for('alunos.logoff')}}">Sair (Olá, {{current_user.nome}})</a>
                    </li>
                    {% else %}
                    <li class="nav-item">             
                      <a class="nav-link" href="{{url_for('alunos.login')}}">Login</a>
                    </li>
                    {% endif %}
                    <!--<li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                      </div>
                    </li>
                    !-->
                  </ul>
                </div>
              </nav>

          
            {% set mensagens = get_flashed_messages(with_categories=true) %} 
            {% if mensagens %}     
            {% for categoria, msg in mensagens %}
                <div class="alert alert-{{categoria}}" role="alert">
                    {{ msg }}
                </div>
            {% endfor %}
            {% endif %}

	        <main>
	        {% block conteudo %}
            {% endblock %}
	        </main>

	    </body>
	</html>

templates/dashboard.html
{% extends 'base.html'%}
{%block conteudo%}

    Bem-vindo!

{%endblock%}

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <!-- Inclua os links para os arquivos CSS e JS do Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-4">
                <h2 class="text-center mb-4">Login</h2>
                {% set mensagens = get_flashed_messages(with_categories=true) %} 
                {% if mensagens %}     
                {% for categoria, msg in mensagens %}
                    <div class="alert alert-{{categoria}}" role="alert">
                        {{ msg }}
                    </div>
                {% endfor %}
                {% endif %}
                
                <form action="{{url_for('alunos.autenticar')}}" method="post">
                    <div class="form-group">
                        <label for="username">Matrícula</label>
                        <input type="text" class="form-control" id="matricula" name="matricula" placeholder="Digite sua matrícula" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Senha</label>
                        <input type="password" class="form-control" id="senha" name="senha" placeholder="Digite sua senha" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/nota_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% set mensagens = get_flashed_messages() %} 
    {% if mensagens %}     
    <div class="alert alert-danger" role="alert">
    {% for msg in mensagens %}
            {{ msg }}
    {% endfor %}
    </div>
    {% endif %}

    <form action="{{url_for('add')}}" method="post">
        Nota: <input type="text" name="valor">
        <button type="submit">Cadastrar</button>
    </form>
</body>
</html>

templates/nota_get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        {% for n in notas %}
            <ul>{{n.id}} - {{n.valor}} </ul>
        {% endfor %}
    </ul>
    
</body>
</html>